# Main Menu
main:
  - name: "Home"
    url: "#home"
    weight: 1

  - name: "About"
    url: "#about"
    weight: 2

  - name: "Services"
    url: "#service"
    weight: 3

  - name: "Resume"
    url: "#resume"
    weight: 5

  - name: "Skills"
    url: "#skills"
    weight: 6

# Footer menu
footer:
  - name: Imprint
    url: imprint
    weight: 1

  - name: Privacy Policy
    url: privacy
    weight: 2
